### ISSUE TITLE
[Intro to IOS] Project 1 - Review my my app #1

### ISSUE THREAD

**Issue by effyyzhang** [effyyzhang/Swift#1]
my app is complete, please review. /cc @codepathreview

**Comment by timothy1ee** [comment]
Good work. This prework is a preview of our weekly project process. Generally, weekly projects take between 5-10 hours to complete the required features and an additional 5-10 hours to complete the optional features. In general, we've seen that the more hours you log, the quicker you improve your proficiency with iOS.

The next step is to schedule a brief phone conversation with me [here](https://www.google.com/calendar/selfsched?sstoken=UVBDTi1jVkx4SldqfGRlZmF1bHR8MGVhNTlkZDFmYzQzODdkNDFhZjQ0NWQyZjFiMDU3Nzg). I have appointment slots most weeks. Admission is rolling, so the sooner you schedule, the better. Once you've selected a time, update the calendar event with a phone number to call you at.

Feel free to make any improvements to the app before we chat, I'll check it one more time right before our call. I give priority to people that demonstrate that they are willing to put a lot of time into this class.

**Comment by effyyzhang** [comment]
Hi, Tim,

I just made an appointment on September 1, but My accident selected two
slots, could you please delete the second one on your side? I can not edit
it on my side.

Also, there is no appointment in August, are the appointment all been
taken, or you didn't schedule any? I'm a little bit worried I applied too
late.

Thanks
Effy

**Comment by timothy1ee** [comment]
Effy,

I deleted the duplicate appointment. All the August appointments were
taken, but look forward to chatting with you soon!

Tim

On Mon, Aug 24, 2015 at 9:46 AM, Effy Zhang notifications@github.com
wrote:

> Hi, Tim,
> 
> I just made an appointment on September 1, but My accident selected two
> slots, could you please delete the second one on your side? I can not edit
> it on my side.
> 
> Also, there is no appointment in August, are the appointment all been
> taken, or you didn't schedule any? I'm a little bit worried I applied too
> late.
> 
> Thanks
> Effy
> 
> On Sat, Aug 22, 2015 at 12:58 PM, Timothy Lee notifications@github.com
> wrote:
> 
> > Good work. This prework is a preview of our weekly project process.
> > Generally, weekly projects take between 5-10 hours to complete the
> > required
> > features and an additional 5-10 hours to complete the optional features.
> > In
> > general, we've seen that the more hours you log, the quicker you improve
> > your proficiency with iOS.
> > 
> > The next step is to schedule a brief phone conversation with me here
> > <
> > https://www.google.com/calendar/selfsched?sstoken=UVBDTi1jVkx4SldqfGRlZmF1bHR8MGVhNTlkZDFmYzQzODdkNDFhZjQ0NWQyZjFiMDU3Nzg
> > .
> > I have appointment slots most weeks. Admission is rolling, so the sooner
> > you schedule, the better. Once you've selected a time, update the
> > calendar
> > event with a phone number to call you at.
> > 
> > Feel free to make any improvements to the app before we chat, I'll check
> > it one more time right before our call. I give priority to people that
> > demonstrate that they are willing to put a lot of time into this class.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/effyyzhang/Swift/issues/1#issuecomment-133748274.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/effyyzhang/Swift/issues/1#issuecomment-134296027.

## 

Timothy Lee
CodePath, Co-founder
512-496-3481
http://codepath.com

**Comment by effyyzhang** [comment]
Hi Tim,

I add some animation for my app and create an issue on Github.

Really hope to be part of this community! Hope to hear from you soon!
Have a great Labor Day weekend~

Effy
